spring:
  application:
    name: eureka-service-a

server:
  port: 2222
  


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/ #http://localhost:1111/
    
