spring:
  application:
    name: eureka-ribbon-client

server:
  port: 3333
  


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1111/eureka/ #http://localhost:1111/
    
